#!/bin/bash
generate_password() {
    local length=$1
    tr -dc 'A-Za-z0-9_@#$%&*' < /dev/urandom | head -c $length
    echo  
}
if [ $# -ne 2 ]; then
    echo 
    exit 1
fi
num_passwords=$1
password_length=$2
for ((i = 1; i <= num_passwords; i++)); do
    generate_password $password_length
done
